#!/usr/bin/env bash

# setup.sh - Prepare the GitLab Rails monolith for local Caproni development.
#
# Copies runtime configuration generated by CNG / the Helm chart from a live
# gitlab-webservice-default pod into the local checkout, then rewrites the
# Rails environment from "production" to "development" so the app can run
# locally (e.g. via mirrord) against the real cluster services.
#
# Only files that are generated at deploy time (i.e. NOT committed to the
# gitlab-rails repo) are fetched.  See the CONFIG_FILES list in section 2.
#
# Prerequisites:
#   - kubectl configured and pointing at the Caproni cluster
#   - A running gitlab-webservice-default deployment in the target namespace
#   - The GitLab Rails repo checked out locally
#
# Usage:
#   .gitlab/caproni/setup.sh [--namespace <ns>] [--context <kubectl-context>]

set -euo pipefail

# Colors
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

# Helper functions for colored output
error() {
  echo >&2 -e "${RED}ERROR: ${1-}${NC}"
}

warn() {
  echo >&2 -e "${YELLOW}WARNING: ${1-}${NC}"
}
success(){
  echo >&2 -e "${GREEN} ${1-}${NC}"
}


# ---------------------------------------------------------------------------
# 0. Parse arguments / set defaults

NAMESPACE="${NAMESPACE:-gitlab}"
KUBE_CONTEXT=""
GITLAB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
POD_BASE="/srv/gitlab"
DEPLOYMENT_LABEL="app=webservice"
CONTAINER="webservice"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --namespace)
      NAMESPACE="$2"
      shift 2
      ;;
    --context)
      KUBE_CONTEXT="$2"
      shift 2
      ;;
    *)
      echo "Unknown argument: $1" >&2
      echo "Usage: $0 [--namespace <ns>] [--context <kubectl-context>]" >&2
      exit 1
      ;;
  esac
done

KUBECTL="kubectl"
if [[ -n "$KUBE_CONTEXT" ]]; then
  KUBECTL="kubectl --context=$KUBE_CONTEXT"
fi

echo "==> GitLab directory : $GITLAB_DIR"
echo "==> Namespace        : $NAMESPACE"
[[ -n "$KUBE_CONTEXT" ]] && echo "==> Context          : $KUBE_CONTEXT"

# ---------------------------------------------------------------------------
# 1. Locate a running pod from the gitlab-webservice-default deployment
#    Picks the first Running pod; aborts if none is found.
# ---------------------------------------------------------------------------

echo ""
echo "==> Locating a running pod in $NAMESPACE with label $DEPLOYMENT_LABEL..."

POD_NAME=""
MAX_RETRIES=120
RETRY_INTERVAL=2
ATTEMPT=0

# Waiting for pod to be found with label webservice
# Logs pod name and status along with namespace if the pod is found but with status other than Running
# Logs "Pod not found with label <label> in naespace <namespace>, retrying in Xs (attempt x/y)" if pod not found
while [[ $ATTEMPT -lt $MAX_RETRIES ]]; do
  POD_NAME=$(
    $KUBECTL get pod -n "$NAMESPACE" \
      -l "$DEPLOYMENT_LABEL" \
      -o jsonpath='{.items[0].metadata.name}' 2>/dev/null || true
  )

  if [[ -z "$POD_NAME" ]]; then
    ATTEMPT=$((ATTEMPT + 1))
    if [[ $ATTEMPT -lt $MAX_RETRIES ]]; then
      echo "Pod not found with label $DEPLOYMENT_LABEL in namespace $NAMESPACE, retrying in ${RETRY_INTERVAL}s (attempt $ATTEMPT/$MAX_RETRIES)..."
      sleep "$RETRY_INTERVAL"
    fi
    continue
  fi

  POD_STATUS=$(
    $KUBECTL get pod -n "$NAMESPACE" \
      -l "$DEPLOYMENT_LABEL" \
      -o jsonpath='{.items[0].status.phase}' 2>/dev/null || true
  )

  if [[ "$POD_STATUS" == "Running" ]]; then
    success "==> Found pod: $POD_NAME in $POD_STATUS status"
    break
  fi

  ATTEMPT=$((ATTEMPT + 1))
  if [[ $ATTEMPT -lt $MAX_RETRIES ]]; then
    echo "Pod $POD_NAME status: $POD_STATUS, retrying in ${RETRY_INTERVAL}s (attempt $ATTEMPT/$MAX_RETRIES)..."
    sleep "$RETRY_INTERVAL"
  fi
done

if [[ -z "$POD_NAME" ]] || [[ "$POD_STATUS" != "Running" ]]; then
  error "No Running webservice pod found in namespace '$NAMESPACE' after $((MAX_RETRIES * RETRY_INTERVAL))s."
  error "       Check: kubectl get pods -n $NAMESPACE -l app=webservice" >&2
  exit 1
fi




# ---------------------------------------------------------------------------
# 2. Copy CNG-generated config files from the pod into $CONFIG_DIR
#
#    These files are written by the Helm chart init containers or the CNG
#    image at pod startup and are NOT committed to the gitlab-rails repo.
#    Paths in CONFIG_FILES are relative to $POD_BASE (/srv/gitlab) in the pod
#    and are mirrored to the same relative path under $GITLAB_DIR locally.
# ---------------------------------------------------------------------------

echo ""
echo "==> Copying CNG-generated config files from pod $POD_NAME..."

CONFIG_FILES=(
  "config/gitlab.yml"
  "config/database.yml"
  "config/cable.yml"
  "config/resque.yml"
  "config/redis.action_cable.yml"
  "config/session_store.yml"
  "config/secrets.yml"
  "config/initializers/smtp_settings.rb"
  "config/puma.rb"
)

COPIED_FILES=()
FAILED_FILES=()

for file in "${CONFIG_FILES[@]}"; do
  local_path="$GITLAB_DIR/$file"
  mkdir -p "$(dirname "$local_path")"
  $KUBECTL cp -n "$NAMESPACE" -c "$CONTAINER" "$POD_NAME:$POD_BASE/$file" "$local_path" >/dev/null 2>&1
  if [[ -f "$local_path" ]]; then
    echo "  ✓ $file"
    COPIED_FILES+=("$file")
  else
    warn "could not copy $file (skipping)"
    FAILED_FILES+=("$file")
  fi
done

echo "Copied ${#COPIED_FILES[@]} files, skipped ${#FAILED_FILES[@]}."

# ---------------------------------------------------------------------------
# 3. Rewrite top-level "production:" key → "development:" in YAML configs
#
#    The Helm chart generates YAML files keyed under "production:".
#    Rails uses the top-level key to select the active config block, so
#    we rename it to "development:" to match RAILS_ENV=development.
#
#    Only the top-level key is replaced (anchored to start-of-line) so that
#    the word "production" inside values (e.g. log paths, URLs) is untouched.
# ---------------------------------------------------------------------------

echo ""
echo "==> Rewriting 'production:' → 'development:' in YAML config files..."

ENV_REWRITE_FILES=(
  "config/gitlab.yml"
  "config/database.yml"
  "config/cable.yml"
  "config/resque.yml"
  "config/redis.action_cable.yml"
  "config/session_store.yml"
  "config/secrets.yml"
)

MODIFIED_FILES=()
UNMODIFIED_FILES=()

for file in "${ENV_REWRITE_FILES[@]}"; do
  file_path="$GITLAB_DIR/$file"
  if [[ -f "$file_path" ]]; then
    sed -i.bak 's/^production:/development:/' "$file_path"
    rm "$file_path.bak"
    MODIFIED_FILES+=("$file")
    echo "  - $file"
  else
    warn "unable to patch $file (skipping)"
    UNMODIFIED_FILES+=("$file")
  fi
done

echo "Rewrote environment key in ${#MODIFIED_FILES[@]} files."

# ---------------------------------------------------------------------------
# 4. Patch database.yml: add gssencmode: disable
#
#    libpq's GSSAPI negotiation triggers a segfault on macOS when connecting
#    to a PostgreSQL server that doesn't support GSSAPI (e.g. CloudNativePG).
#    Setting gssencmode: disable skips the negotiation entirely.
# ---------------------------------------------------------------------------

echo ""
echo "==> Patching config/database.yml: adding gssencmode: disable..."

DB_YML="$GITLAB_DIR/config/database.yml"
if [[ -f "$DB_YML" ]]; then
  # Insert "gssencmode: disable" on the line after every "adapter: postgresql",
  # preserving the same leading whitespace.  The sed expression is POSIX-
  # compatible and works on both GNU sed (Linux) and BSD sed (macOS).
  #
  sed -i.bak 's/^\([ \t]*\)adapter: postgresql$/\1adapter: postgresql\n\1gssencmode: disable/' "$DB_YML"
  rm "$DB_YML.bak"
  echo "  ✓ config/database.yml"
else
  warn "config/database.yml not found – skipping gssencmode patch"
fi

# ---------------------------------------------------------------------------
# 5. Write static vite.gdk.json
#
#    vite.gdk.json is committed to the repo and should always use 127.0.0.1
#    so that the Vite dev server is reachable via port-forward.  Writing it
#    here is a no-op in most cases but ensures correctness if the file was
#    regenerated or replaced (e.g. by gdk rake generate_config_files).
# ---------------------------------------------------------------------------

echo ""
echo "==> Writing static config/vite.gdk.json..."

cat > "$GITLAB_DIR/config/vite.gdk.json" <<'EOF'
{
  "enabled": true,
  "public_host": "127.0.0.1",
  "host": "127.0.0.1",
  "port": 3038,
  "hmr": {
    "clientPort": 3038,
    "host": "127.0.0.1",
    "protocol": "ws"
  }
}
EOF
echo "  ✓ config/vite.gdk.json"

# ---------------------------------------------------------------------------
# 6. Summary
# ---------------------------------------------------------------------------

echo ""
success "==> Setup complete."
success ""
success "  Copied: ${COPIED_FILES[*]:-none}"
[[ ${#FAILED_FILES[@]} -gt 0 ]] && success "  Skipped : ${FAILED_FILES[*]}"
success "  Rewritten to development env: ${MODIFIED_FILES[*]:-none}"
success "  Unable to modify files: ${UNMODIFIED_FILES[*]:-none}"
success ""
echo 'Next: Run `caproni run`'
