---
name: update_webhook
description: Grants the ability to update webhooks
boundaries:
  - group
  - project
  - instance
permissions:
  - update_webhook
  - update_webhook_custom_header
  - update_webhook_url_variable
