---
name: ci_skip_redundant_pipeline_cache_expiration
description:
feature_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/594454
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/231372
rollout_issue_url: https://gitlab.com/gitlab-org/gitlab/-/work_items/596729
milestone: '19.0'
group: group::ci platform
type: gitlab_com_derisk
default_enabled: false
