# frozen_string_literal: true

module Gitlab
  module Import
    class IidPreallocator
      # Maps each CE resource type to a tracker lambda and a scope_resolver lambda.
      #
      # tracker: called with (scope_value, max_iid) to pre-allocate the IID.
      #   Uses the track_*_iid! class methods generated by AtomicInternalId.
      #   See app/models/concerns/atomic_internal_id.rb
      #
      # scope_resolver: called with the importable (Project or Group) to resolve
      #   the correct scope object. Returns nil for inapplicable scopes (e.g.
      #   group_milestones on a project with no group) - execute skips those.
      TRACKABLE_RESOURCES = {
        issues: {
          tracker: ->(scope, iid) { ::Issue.track_namespace_iid!(scope, iid) },
          scope_resolver: ->(importable) { importable.project_namespace }
        },
        merge_requests: {
          tracker: ->(scope, iid) { ::MergeRequest.track_target_project_iid!(scope, iid) },
          scope_resolver: ->(importable) { importable }
        },
        project_milestones: {
          tracker: ->(scope, iid) { ::Milestone.track_project_iid!(scope, iid) },
          scope_resolver: ->(importable) { importable }
        },
        group_milestones: {
          tracker: ->(scope, iid) { ::Milestone.track_group_iid!(scope, iid) },
          scope_resolver: ->(importable) { importable.group }
        },
        ci_pipelines: {
          tracker: ->(scope, iid) { ::Ci::Pipeline.track_project_iid!(scope, iid) },
          scope_resolver: ->(importable) { importable }
        },
        design_management_designs: {
          tracker: ->(scope, iid) { ::DesignManagement::Design.track_project_iid!(scope, iid) },
          scope_resolver: ->(importable) { importable }
        }
      }.freeze

      def self.trackable_resources
        TRACKABLE_RESOURCES
      end

      def self.from_file(importable, path)
        return unless File.exist?(path)

        content = File.read(path)
        parsed = Gitlab::Json.safe_parse(content)

        unless parsed.is_a?(Hash)
          ::Import::Framework::Logger.warn(
            message: 'IidPreallocator: skipping preallocation, invalid content in max_iids file'
          )
          return
        end

        symbolized = parsed.transform_keys(&:to_sym)
        valid, invalid = symbolized.partition { |_, v| v.is_a?(Integer) && v > 0 }.map(&:to_h)

        if invalid.any?
          ::Import::Framework::Logger.warn(
            message: 'IidPreallocator: ignoring invalid IID entries in max_iids file',
            invalid_entries: invalid
          )
        end

        new(importable, valid).execute
      rescue EncodingError, JSON::ParserError
        ::Import::Framework::Logger.warn(
          message: 'IidPreallocator: skipping preallocation, invalid content in max_iids file'
        )
      rescue StandardError => e
        ::Import::Framework::Logger.warn(
          message: 'IidPreallocator: skipping preallocation, failed to read max_iids file',
          error: e.message
        )
      end

      # @param importable [Project, Group] the project or group being imported into
      # @param max_iids [Hash<Symbol, Integer>] resource type => max IID from source
      #   e.g. { issues: 142, merge_requests: 37, ci_pipelines: 891 }
      def initialize(importable, max_iids)
        @importable = importable
        @max_iids = max_iids
      end

      def execute
        self.class.trackable_resources.each do |resource, config|
          max_iid = @max_iids[resource]
          next unless max_iid

          scope_value = config[:scope_resolver].call(@importable)
          next unless scope_value

          config[:tracker].call(scope_value, max_iid)
        end
      end
    end
  end
end

Gitlab::Import::IidPreallocator.prepend_mod
