---
name: load_balancer_force_release_hosts
introduced_by_url: https://gitlab.com/gitlab-org/gitlab/-/merge_requests/230066
rollout_issue_url:
milestone: '18.11'
group: group::database
type: ops
default_enabled: false
